### ISSUE TITLE
convert.py does not open stream for -of other than xlsx

### ISSUE THREAD

**Issue by Eszti** [recski/brise-plandok#10]
NOTE: this issue was detected on `dev`

Executing 

```bash
python brise_plandok/convert.py \
    -i XLSX \
    -if ~/research/data/brise/ann/$1.xlsx \
    -o JSON \
    -of ~/research/data/brise/ann/$1.json
```

results in

```bash
Traceback (most recent call last):
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 391, in <module>
    main()
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 387, in main
    converter.convert(input_stream, output_stream)
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 358, in convert
    self.write(doc, output_stream)
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 348, in write
    self.write_json(doc, stream)
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 324, in write_json
    stream.write(json.dumps(doc))
AttributeError: 'str' object has no attribute 'write'
  ```

**Comment by Eszti** [comment]
This also applies for inputs.

Executing

```bash
python brise_plandok/convert.py \
    -i JSON \
    -if ~/research/data/brise/json/$1.jsonl \ 
    -o XLSX \
    -of ~/research/data/brise/ann/$1.xlsx
```

results in

```bash
Traceback (most recent call last):
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 391, in <module>
    main()
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 387, in main
    converter.convert(input_stream, output_stream)
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 357, in convert
    for doc in self.read(input_stream):
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 313, in read
    yield from self.read_json(stream)
  File "/home/eszter/research/brise-plandok/brise_plandok/convert.py", line 309, in read_json
    yield json.loads(line)
  File "/home/eszter/.pyenv/versions/3.9.6/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/eszter/.pyenv/versions/3.9.6/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/eszter/.pyenv/versions/3.9.6/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by recski** [comment]
@Eszti is this still relevant?

**Comment by Eszti** [comment]
I think, I did not use other functions of this script, so I don't know. But this file should be investigated for deletion, as I mostly used new components.
